<?php

/**
 * Implements of hook_menu().
 */
function my_contacts_menu() {
  $items = array();

  $items['my-contacts'] = array(
    'title' => t('My Contacts'),
    'page callback' => 'my_contacts_contact_list',
    'access arguments' => array('access content'),
    'file' => 'my_contacts.inc',
  );
  $items['my_contacts/ajax-add-contact'] = array(
    'page callback' => 'my_contacts_ajax_add_contact',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'my_contacts.inc',
  );

  return $items;
}

/**
 * Implementation of hook_block_info().
 */
function my_contacts_block_info() {
  $blocks = array();
  $blocks['my_contacts_profile_block'] = array(
    'info' => t('My Contacts List Block'),
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function my_contacts_block_view($delta='') {

  $block = array();
  switch ($delta) {
    case 'my_contacts_profile_block':
      module_load_include('inc', 'my_contacts', 'my_contacts');
      $block['subject'] = t('My Contacts');
      $block['content'] = my_contacts_contact_list();
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 *
 * Information on hook theme http://groups.drupal.org/node/14274#comment-57950.
 *    1. hook_theme which adds an array of callbacks and their arguments to the
 *      theme registry. I didn't realize that I had to visit the modules page to
 *      rebuild the theme registry before it would be added.
 *    2. The themable function itself which starts with theme_ followed by the
 *      function name that was added to the registry with hook_theme.
 *    3. theme("whatever_function, $whatever_argument, $whatever_argument ")
 *     which actually calls the function.
 */
function my_contacts_theme() {
  return array(

    'my_contacts_create_contact' => array(
      'variables' => array(
        'uid' => NULL,
        'cid' => NULL,
        'text' => FALSE,
      ),
      'file' => 'my_contacts.inc',
    ),
  );
}